### ISSUE TITLE
Opening Videos in Modal instead of Opening on Page Itself

### ISSUE THREAD

**Issue by menikhilpandey** [coding-blocks/bytecast.codingblocks.com#5]
Currently the videos are being played on the page itself. It will be better in terms of UI/UX if we use a modal instead. Mock up for the same is provided. 

![screenshot from 2017-05-16 21 53 13](https://cloud.githubusercontent.com/assets/16885925/26116828/1d890d4c-3a82-11e7-90e4-11201e54f3b8.png)

**Comment by arunikayadav42** [comment]
can somebody tell me please what language is it based on?and help me get started with it.
